<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KeyboardSpeed.Core\KeyboardSpeed.Core.csproj" />
    <ProjectReference Include="..\KeyboardSpeed.Input.Windows\KeyboardSpeed.Input.Windows.csproj" />
    <ProjectReference Include="..\KeyboardSpeed.Bluetooth.Windows\KeyboardSpeed.Bluetooth.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
